In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])

In [3]:
print(A)

[[1 2]
 [3 4]]


In [4]:
print(type(A))

<class 'numpy.ndarray'>


In [5]:
print(A.T)

[[1 3]
 [2 4]]


In [6]:
B = np.transpose(A)
print(B)

[[1 3]
 [2 4]]


In [7]:
result = np.dot(A,B)
print(result)

[[ 5 11]
 [11 25]]


In [8]:
print(B[1,0])

2


In [9]:
print(B.shape)

(2, 2)


In [10]:
arr = np.array([1,2,3,4,5,6])

In [11]:
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [12]:
print(arr.reshape(-1))

[1 2 3 4 5 6]


In [13]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr1.dtype

dtype('int32')

In [15]:
arr = np.array([1,2,3], dtype = np.float64)

In [16]:
arr.itemsize

8

In [17]:
arr

array([1., 2., 3.])

In [18]:
arr.size

3

In [19]:
A = np.array([[1,2],[3,4],[5,6]])

In [20]:
A.shape

(3, 2)

In [21]:
np.array([2,2])

array([2, 2])

In [22]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [23]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

## Arange

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(5,2)

array([], dtype=int32)

In [26]:
np.arange(1,5,2)

array([1, 3])

## Linspace

In [27]:
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

## Reshaping a matrix

In [28]:
a = np.array([1,2,3,4,5,6])

In [29]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## Flattening a matrix

In [30]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [31]:
a.sum(axis=0)

21

In [32]:
a

array([1, 2, 3, 4, 5, 6])

## Minimum Value, Maximum Value and Sum

In [33]:
a = np.array([[1,2],[3,4],[5,6]])

In [34]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a.min()

1

In [36]:
a.max()

6

In [37]:
a.sum()

21

In [38]:
a.sum(axis=0)

array([ 9, 12])

## Square Root of an array

In [39]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

## Dot Product

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [42]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

# Eigen Value and Eigen Vector

In [43]:
import numpy as np
from numpy.linalg import eig

In [44]:
A = np.array([[4,2],[7,3]])

In [45]:
w,v = eig(A)

In [46]:
print("Eigen Value:",w)

Eigen Value: [ 7.27491722 -0.27491722]


In [47]:
print("Eigen Vector:",v)

Eigen Vector: [[ 0.52119606 -0.42376194]
 [ 0.85343697  0.9057736 ]]


## Determinant of Matrix

In [48]:
from numpy.linalg import det

In [49]:
A = np.array([[1,4],[4,2]])

In [50]:
B = det(A)

In [51]:
print("Determinant of A:",B)

Determinant of A: -14.000000000000004


## Inverse of a matrix

In [52]:
from numpy.linalg import inv

In [53]:
B = inv(A)

In [54]:
print("Inverse of A:",B)

Inverse of A: [[-0.14285714  0.28571429]
 [ 0.28571429 -0.07142857]]


## Indexing in array

In [55]:
arr = np.array([[6,7,8],[1,2,3],[9,3,3]])
arr

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 3]])

In [56]:
arr[0:2,2]

array([8, 3])

## Iterating Through an array

In [57]:
arr

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 3]])

In [58]:
for cell in arr.flat:
    print(cell)

6
7
8
1
2
3
9
3
3


## Stacking

In [59]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

### Vertical Stack

In [61]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### Horizontal Stack

In [62]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [63]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
b = a>4

In [65]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [66]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])